name: Update Job Postings

on:
  workflow_dispatch: # 수동 실행을 위해 추가
  schedule:
    - cron: "0 0 * * 1" # 매주 월요일 00:00 UTC (한국 시간 오전 9시)에 실행

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: false
          ref: 'main'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-dotenv

      - name: Run script to update README
        env:
          FSS_API_KEY: ${{ secrets.FSS_API_KEY }}
        run: python Chapter_10/update_jobs.py

      - name: Display README content for debugging
        run: |
          echo "--- Content of README.md after script run ---"
          cat README.md
          echo "--------------------------------------------------------"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          if ! git diff --staged --quiet; then
            git commit -m "chore: 주간 채용 공고 업데이트"
            git push
          else
            echo "No changes to commit."
          fi